name: Ideia
description: Sugira uma melhoria
labels: [enhancement]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Como imagina que funcione?
